spring:
  datasource:
    url: jdbc:postgresql://${PROD_POSTGRES_URL}:${PROD_POSTGRES_PORT}//${PROD_POSTGRES_DATABASE}
    username: ${PROD_POSTGRES_USERNAME}
    password: ${PROD_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update

spring.security.oauth2.client:
  registration:
    kakao:
      redirect-uri: ${PROD_URL}/login/oauth2/code/kakao

logging:
  level:
    root: info