spring:
  datasource:
    url: jdbc:postgresql://${DEV_POSTGRES_URL}:${DEV_POSTGRES_PORT}/${DEV_POSTGRES_DATABASE}
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.format_sql: true
    defer-datasource-initialization: true
    hibernate.ddl-auto: update

spring.security.oauth2.client:
  registration:
    kakao:
      redirect-uri: ${DEV_URL}/login/oauth2/code/kakao