spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/kiosk
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.format_sql: true
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
  
  data:
    redis:
      host: localhost
      port: 16379

spring.security.oauth2.client:
  registration:
    kakao:
      redirect-uri: ${DEV_URL}/login/oauth2/code/kakao